# Generated by Django 6.0.4 on 2026-05-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
