# Generated by Django 6.0.4 on 2026-05-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document'),
        ),
    ]
